### ISSUE TITLE
Multi touching fingers

### ISSUE THREAD

**Issue by ntsounosp** [tyzlmjj/PagerBottomTabStrip#10]
Hello,

Actually tabs works perfect and animation was amazing. But i would like to help me because i'm sticking in a problem when i touch tabs with more than 1 finger simultaneously or very fast, then my application brings out this error: java.lang.IllegalStateException: No host
I'm on my wits' end...Do you have any idea?

Thanks in advance for your time

**Comment by tyzlmjj** [comment]
this is not PagerBottomTabStrip's  fault,the error is caused by the test project usingFragment animation .to remove the fragment animation is no problem

Remove  the following code in MainActivity:
```
transaction.setCustomAnimations (R.anim.push_up_in, R.anim.push_up_out);
```
 : )

**Comment by ntsounosp** [comment]
Thanks for your immediate response, i appreciate a lot!! Great work!! :)
