### ISSUE TITLE
可以不设置（默认）selectedColor吗

### ISSUE THREAD

**Issue by qdxxxx** [tyzlmjj/PagerBottomTabStrip#16]
addTabItem 的时候如果设置了选中图片和未选中图片，怎么取消SelectedColor，因为如果有SelectedColor，设置选中图片就没什么作用了。

**Comment by tyzlmjj** [comment]
所有图标的选中颜色都是纯色且统一的，官方的规范是这样的。所以只能设置一种颜色。

**Comment by tyzlmjj** [comment]
选中的图标按谷歌的规范只能是纯色的
