### ISSUE TITLE
我想问下如何只改变一个tab的选中背景?

### ISSUE THREAD

**Issue by peng8350** [tyzlmjj/PagerBottomTabStrip#17]
我想实现就是你效果图里面只改变单一tab的效果图,并不是整个bottombar的背景。我看了以下你的教程,好像有一个setMessageBackgroundColor的方法是可以解决我的问题,但是我设置了没效果。
       controller = bottom_Bar.builder()
                .setMessageBackgroundColor(testColors[3])
                .addTabItem(tabItemBuilder)
                .addTabItem(R.drawable.tab1_normal,R.drawable.tab1_selected ,"位置", testColors[1])
                .addTabItem(R.drawable.main_tab1, "搜索", testColors[2])
                .addTabItem(R.drawable.main_tab1, "帮助", testColors[3])
                .build();
代码在上面,已经设置进去了,没效果。

**Comment by tyzlmjj** [comment]
不太理解你说的什么意思。仔细看下我写的指南，效果图里面的都可以实现！！

**Comment by peng8350** [comment]
就是你的那个demo1.gif效果图,我就是想要那种散开的效果,只在一个tab散开

**Comment by tyzlmjj** [comment]
没有这种效果！

**Comment by tyzlmjj** [comment]
刚弄错了，demo1.gif的效果肯定是可以实现的，我都是截图的！
但是这个波纹效果我是直接用官方的，只在5.0以上有效果
