### ISSUE TITLE
你的类库下不下来?

### ISSUE THREAD

**Issue by LonelyMushroom** [tyzlmjj/PagerBottomTabStrip#2]
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'me.majiajie:pager-bottom-tab-strip:1.0.0'
}  --------Moudle:app

allprojects {
    repositories {
        mavenCentral();
        jcenter();
    }
}  -----Maven

**Comment by tyzlmjj** [comment]
可以下的，检查下网络状况吧！
