### ISSUE TITLE
Support for kotlin

### ISSUE THREAD

**Issue by hy9be** [tyzlmjj/PagerBottomTabStrip#20]
Kotlin的runtime有对jetbrains那个annotation的库的依赖，然后他们一直不肯去掉。不知道咱们这个库方不方便出一个for Kotlin的版本，去掉对这个库的依赖。

不然dexing的时候出错说multiple dex files.

谢谢！

**Comment by tyzlmjj** [comment]
只是做了一些非空的注解，你想去掉可以拉源码改一下就行了

**Comment by hy9be** [comment]
哦这样那我直接改好了。谢谢！
