### ISSUE TITLE
怎么设置小红点，demo也没有啊

### ISSUE THREAD

**Issue by xueyaolive** [tyzlmjj/PagerBottomTabStrip#21]
//用TabItemBuilder构建一个导航按钮
        TabItemBuilder tabItemBuilder = new TabItemBuilder(this).create()
                .setDefaultIcon(img[0])
                .setText(title[0])
                .setSelectedColor(ContextCompat.getColor(this, R.color.color_rest))
                .setTag("A")
                .setDisplayOval//此行出错
                .build();

**Comment by tyzlmjj** [comment]
在构建好导航栏后，可以获取Controller实例，用它做后续操作

仔细看我写的文档https://github.com/tyzlmjj/PagerBottomTabStrip/wiki/%E6%8E%A7%E5%88%B6%E5%AF%BC%E8%88%AA%E6%A0%8F
