### ISSUE TITLE
在红点显示之后怎么取消红点的显示？

### ISSUE THREAD

**Issue by liwk** [tyzlmjj/PagerBottomTabStrip#22]
在某个index上设置了带数字的红点，怎么在点过之后index之后取消红点的显示？

**Comment by zhanghaotian123** [comment]
点击之后会出发index上绑定的点击事件
![image](https://github.com/tyzlmjj/PagerBottomTabStrip/assets/59438626/f1a2b1c6-7471-47ed-89f9-5f270e410422)
点击之后，设置为0，就好啦
mNavigationController.setMessageNumber(0,0);
