### ISSUE TITLE
博主你是我楷模，不要这么傲娇

### ISSUE THREAD

**Issue by dyfan** [tyzlmjj/PagerBottomTabStrip#24]
你的源码我再看，来一篇食用指南嘛。不知道怎么下口，按照什么方式吃你的这个源码

**Comment by tyzlmjj** [comment]
主要就是用了 Canvas,Paint,Bitmap 这些画图的API,真的没什么好讲的.
会用这些类就可以实现了

**Comment by dyfan** [comment]
看来基础比较弱鸡了，谢谢啦。我感觉监听器吧oldintex传出去更方便使用。个人建议哈。

**Comment by dyfan** [comment]
怎么去修改字体的大小，底部导航栏的宽度，
我改了底部导航栏的宽度和字体的大小，但是导航栏的每一个item的图标和文字就是一个居中的状态了，看到你是用canvas画的，看不懂。。。可以指点一下吗

**Comment by tyzlmjj** [comment]
网上搜下资料多的是呀！

**Comment by dyfan** [comment]
看的我是一脸懵逼啊。~~~~(>_<)~~~~暂时先关闭吧，修改了一些参数，算是达到效果了。
