### ISSUE TITLE
item竖着排列的情况，什么时候可以添上

### ISSUE THREAD

**Issue by zhuxiaohong** [tyzlmjj/PagerBottomTabStrip#26]

**Comment by tyzlmjj** [comment]
关于这个项目，我有很多想法，一直想改！但是需要蛮多时间的，最近手上有应用在开发，真的提不起劲来改这个！

等我把上手的项目做完再来更新这个吧...

顺便提一下，Android最新的支持包里面已经有一个官方版本的实现了[BottomNavigationView](https://developer.android.com/reference/android/support/design/widget/BottomNavigationView.html)。
