### ISSUE TITLE
自定义的内容比较少

### ISSUE THREAD

**Issue by likealeodog** [tyzlmjj/PagerBottomTabStrip#29]
本来是很好用的一个组件，但是自定义的属性太少了，比如整个控件的高度，图片与文字之间的距离，文字的大小，item选中后的背景变化，如果能做到像RadioButton在RadioGroup中的这些属性定义的话就完善了，现在的功能和属性满足不了项目需求。。。源码里面有很多的值都固定了，能增加这些属性的设置吗？额 顺便问句有没有支持RadioButton 的红点组件。。。谢谢

**Comment by tyzlmjj** [comment]
无规矩不成方圆，每个人的设计需求可能都有所不同，我选择了按官方的设计来做。

**Comment by likealeodog** [comment]
官网的设计只是作为一个示范的东西，它是指导开发者要符合怎样的一种规范而不是让开发者完完全全地照着去做固步自封，这个组件作为你自己的，你如果有能力既符合官网规范又有自己的拓展性这个控件才算是易用的组件，只是一个建议而已，可以当我没说。
