### ISSUE TITLE
material风格的tab

### ISSUE THREAD

**Issue by wlyy460** [tyzlmjj/PagerBottomTabStrip#31]
同时快速按下多个选项导航Iem时，出现item的可能文字部分显示异常，文字颜色有些和其他的文字颜色显示不一字，或者变暗，或者选中的图标下的文字没有缩放，需要多次尝试测试

**Comment by tyzlmjj** [comment]
v2版本 在5.0以下的系统是会出现这种状况。因为我完全改掉了实现方式，V1版本是没有这个问题的，如果只用material 风格可以使用v1版本

**Comment by wlyy460** [comment]
v1版本有底部红色圆点消息功能吗，这个需要

**Comment by wlyy460** [comment]
不过Android 5.0也有这个问题，还没时间仔细研究过源码，希望作者后续能有所更新解决新的问题，谢谢

**Comment by tyzlmjj** [comment]
最新的2.2.0版本已经修复了这个问题
