### ISSUE TITLE
自定义Item

### ISSUE THREAD

**Issue by instanceofz** [tyzlmjj/PagerBottomTabStrip#34]
我想实现中间的item凸起的效果，但是凸起后，虽然效果是实现了，但是点击效果会出问题。就是其他item上方空白的地方大概20dp的高度依然有点击事件，现在我不想要空白那里的点击事件。有没有什么好的解决办法呢？

**Comment by tyzlmjj** [comment]
我的DEMO中有中间Item凸起的例子,你看一拉一份代码看看

**Comment by instanceofz** [comment]
我就是用你demo里面的啊

**Comment by tyzlmjj** [comment]
我DEMO里面的点击事件和效果都没有问题，我在手机和虚拟机上都测过
