### ISSUE TITLE
第一个fragment的页面显示异常空白

### ISSUE THREAD

**Issue by wlyy460** [tyzlmjj/PagerBottomTabStrip#36]
使用最新版本2.2.1后，第一个fragment的页面显示异常空白，是什么原因呢？急需解决，谢谢！

**Comment by tyzlmjj** [comment]
我自己项目中使用没有任何问题呀，Demo里面也是好的。

**Comment by wlyy460** [comment]
目前已解决，谢谢回复 # @

**Comment by tyzlmjj** [comment]
默认情况下是选择第一项的，但是初始化的时候是不会有第一项被选中的回调的
