### ISSUE TITLE
求问ViewPager如何设置不能左右滑动

### ISSUE THREAD

**Issue by wheatdamon** [tyzlmjj/PagerBottomTabStrip#37]
看了demo阁下是用ViewPager管理Fragment，求问ViewPager如何设置不能左右滑动

**Comment by tyzlmjj** [comment]
[NoTouchViewPager](https://github.com/tyzlmjj/PagerBottomTabStrip/blob/master/app/src/main/java/me/majiajie/pagerbottomtabstriptest/other/NoTouchViewPager.java)
