### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ruanbaojun1105** [tyzlmjj/PagerBottomTabStrip#39]
添加item的时候应该加个drawable类型，

**Comment by tyzlmjj** [comment]
好吧，有空我会加一个方法！

**Comment by chimpan** [comment]
没找到有设置图标和文字间距的

**Comment by tyzlmjj** [comment]
@chimpan 按照材料设计的规范是不需要修改这些的，你要自定义可以用[自定义](https://github.com/tyzlmjj/PagerBottomTabStrip/wiki/V2_%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95)的方法

**Comment by ruanbaojun1105** [comment]
public MaterialBuilder addItem(Drawable drawable,Drawable checkedDrawable,String title,@ColorInt int chekedColor){
            ViewData data = new ViewData();
            data.drawable = drawable;
            data.checkedDrawable = checkedDrawable;
            data.title = title;
            data.chekedColor = chekedColor;
            itemDatas.add(data);
            return MaterialBuilder.this;
        }
加了这个我就省了你的包
![image](https://user-images.githubusercontent.com/7459297/30359078-fc8db7a8-987a-11e7-865a-711cb5bff95a.png)

**Comment by tyzlmjj** [comment]
新发了版本2.2.3
