### ISSUE TITLE
tab高度问题

### ISSUE THREAD

**Issue by AIlll** [tyzlmjj/PagerBottomTabStrip#40]
高度是不是默认56dp才有居中效果，我改成比如40dp，tab就无法垂直居中了，往下偏移

**Comment by tyzlmjj** [comment]
假如你使用材料设计风格的，那么必须是56dp的。如果你是用自定义布局的，那么高度就随你定

**Comment by AIlll** [comment]
@tyzlmjj  用的就是custom方法，只有一个图标的item，参考的demo，tab高度还是只有56dp才居中

**Comment by tyzlmjj** [comment]
我刚才测试了以下，DEMO里的CUSTOM2 设置导航栏高度为40确实是无法居中，是因为父布局做了一些限制。你可以把item的高度从match_parent改为40dp，就可以解决你的问题。
我后续会更新一个版本调整这个布局策略。感谢你的反馈！
