### ISSUE TITLE
选中的tab，不能在修改tab样式

### ISSUE THREAD

**Issue by AlvinQiang** [tyzlmjj/PagerBottomTabStrip#42]
tab被选中后，再次点击选中的tab时，虽然有监听，但是并不能再次对选中的tab的文字图形样式在进行修改了，建议添加个监听，可以在SpecialTab中进行自定义已选中的tab样式

**Comment by tyzlmjj** [comment]
确实，对于自定义可能更加方便。我会在下一个小版本中添加这个方法

**Comment by tyzlmjj** [comment]
2.2.5版本添加了一个回调
