### ISSUE TITLE
选中的图标无法查看

### ISSUE THREAD

**Issue by ruanbaojun1105** [tyzlmjj/PagerBottomTabStrip#43]
![image](https://user-images.githubusercontent.com/7459297/32868319-a42ef3f6-caac-11e7-8287-ee4e4f3b3015.png)

**Comment by ruanbaojun1105** [comment]
我传了两个drawable才这样，传一个现在看来没问题

**Comment by ruanbaojun1105** [comment]
不过图标都不是一个样子

**Comment by ruanbaojun1105** [comment]
![image](https://user-images.githubusercontent.com/7459297/32868595-00a085f4-caae-11e7-8cad-d3f3104e3ae4.png)

**Comment by tyzlmjj** [comment]
如果用的是材料设计风格的样式，那就把图片的空白部分做成透明的

**Comment by ruanbaojun1105** [comment]
现在有好的方法解决我的问题吗

**Comment by ruanbaojun1105** [comment]
@tyzlmjj

**Comment by tyzlmjj** [comment]
你的图片不适合。如果你要用材料设计风格的样式，就要把你的图片空白部分改成透明的。因为在材料设计的样式里面，所有图标都是染色过的

**Comment by ruanbaojun1105** [comment]
好吧  自己切下图
