### ISSUE TITLE
NormalItemView的未读数

### ISSUE THREAD

**Issue by hegelsu** [tyzlmjj/PagerBottomTabStrip#45]
实际上客户的需求是要求显示实际的未读数，也就是可能会出现987的数字，能支持全显么？

**Comment by tyzlmjj** [comment]
我写的标记是只能到99+的，暂时是不支持显示三位数字的。你这个需求很少见啊！后续我再考虑看看吧。
假如你现在想实现，只能是自定义了

**Comment by hegelsu** [comment]
不急，因为在给一个客户写的程序，他们就要求显示实际值，他们也是做平台，所以基本也不会超过99，但是他们要求这里是多少就显示多少，现在我想升级一些组件，我是想着如果能支持，就不用我再定义了

**Comment by hegelsu** [comment]
自己定义了一个，效果如下：
![1](https://user-images.githubusercontent.com/6879123/34428566-2e77cfbc-ec89-11e7-90b6-6dde14dad618.png)
使用的类库：https://github.com/Caij/BadgeTextView

**Comment by tyzlmjj** [comment]
可以设置小红点的呀

**Comment by hegelsu** [comment]
Set...Oval这个没有找到呢

**Comment by tyzlmjj** [comment]
你看我的demo里面都有写的
