### ISSUE TITLE
MyProject error

### ISSUE THREAD

**Issue by re-LIFE** [tyzlmjj/PagerBottomTabStrip#46]
i was implement your bottomtap special to my project but it crash running , can you check my code??
https://github.com/re-LIFE/TugasAkhirAndroid thank for your attention,

note: im newbie

**Comment by tyzlmjj** [comment]
ERROR:
```
android.view.InflateException: Binary XML file line #0: Error inflating class me.majiajie.pagerbottomtabstriptest.other.NoTouchViewPager
```

in `activity_special.xml`
`me.majiajie.pagerbottomtabstriptest.other.NoTouchViewPager` never existed

**Comment by re-LIFE** [comment]
Thanks for the reply,,

So i must change (me.majiajie.pagerbottomtabstriptest.other.NoTouchViewPager) with my package??

**Comment by re-LIFE** [comment]
![remove](https://user-images.githubusercontent.com/27994247/34457989-c13911b4-edf4-11e7-9cb1-be781dd28bcf.png)
and what is this????
