### ISSUE TITLE
无法将Drawable设置为图标？

### ISSUE THREAD

**Issue by yedajiang44** [tyzlmjj/PagerBottomTabStrip#48]
框架目前好像只能设置资源里的Drawable，但是不能直接将Drawable设置为图标？是我姿势不对么？
`Drawable ic;`
`PageNavigationView tab;`
`//........`
`NavigationController navigationController = tab.material().addItem(ic,"主页").build()`

目前是无法将ic设置为图标。。。。

**Comment by tyzlmjj** [comment]
仔细看重载的方法，可以设置的
