### ISSUE TITLE
底部图标问题

### ISSUE THREAD

**Issue by zofnk** [tyzlmjj/PagerBottomTabStrip#49]
你好 , material下是不是只能使用纯色的图标(不知道是不是Google的设计规范强制如此)? 
我即想实现选中后Icon和字体放大的效果 又想使用UI给的彩色的Icon 
用material只能用纯色 , 用custom的话又没有那个凸起效果。
而且material的话好像也不能自定义TabItem的布局?

**Comment by tyzlmjj** [comment]
是的，材料设计风格的我是按设计规范写的！只能使用纯色图标，因为所有图标都是染色过的

**Comment by zofnk** [comment]
那要怎么自定义TabItem才能有Material Design风格(选中放大Icon和字体)又能让图标是彩色的?

**Comment by tyzlmjj** [comment]
放大缩小无非是一个动画效果，你可以自己写这个动画。自定义的时候选中事件都是有回调的

**Comment by zofnk** [comment]
get√ 我去试试。
