### ISSUE TITLE
how to create material 3?

### ISSUE THREAD

**Issue by re-LIFE** [tyzlmjj/PagerBottomTabStrip#52]
how to create material image 3 ???

**Comment by re-LIFE** [comment]
![image](https://user-images.githubusercontent.com/27994247/40874790-f54056da-669d-11e8-83e9-2679421b44fb.png)

**Comment by tyzlmjj** [comment]
```
...
pageBottomTabLayout.material()
                ...
                .setMode(MaterialMode.CHANGE_BACKGROUND_COLOR)
                .build();
```

**Comment by re-LIFE** [comment]
Thanks for the answer ,, i have more question,  i have 3fragment how to implement it for bottombar? Im still confused , it different between tablayout(normal)

**Comment by tyzlmjj** [comment]
```
NavigationController navigationController = tab.material()
        ...
        .build();

// use ViewPager
navigationController.setupWithViewPager(viewPager);

// or add listener
navigationController.addTabItemSelectedListener(new OnTabItemSelectedListener() {
            @Override
            public void onSelected(int index, int old) {
            }
            @Override
            public void onRepeat(int index) {
            }
        });
```

**Comment by re-LIFE** [comment]
thankyou verymuch..

**Comment by re-LIFE** [comment]
how to add action menu and navdrawer in bottombar ?? can you give me link ?? i will search in gogle

**Comment by tyzlmjj** [comment]
Don't understand what you mean. 
You can see my demo
https://github.com/tyzlmjj/PagerBottomTabStrip/tree/master/app
