### ISSUE TITLE
SpecialActivity这个中间按钮如果不是切换到frament而是直接做其它操作，如打开扫码界面等。怎么处理点击操作的？

### ISSUE THREAD

**Issue by live17909** [tyzlmjj/PagerBottomTabStrip#56]
SpecialActivity这个中间按钮如果不是切换到frament而是直接做其它操作，如打开扫码界面等。怎么处理点击操作的？

**Comment by zhanlanzhiyu** [comment]
仔细看说明[后续控制部分](https://github.com/tyzlmjj/PagerBottomTabStrip/wiki/V2_%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA)

**Comment by zhanlanzhiyu** [comment]
> > > > > QQ号

**Comment by tyzlmjj** [comment]
https://github.com/tyzlmjj/PagerBottomTabStrip/wiki/FAQ
