### ISSUE TITLE
波纹扩散的问题

### ISSUE THREAD

**Issue by mattxzhang** [tyzlmjj/PagerBottomTabStrip#6]
请问一下，波纹扩散的效果是，appcompat带的，还是你代码中自己绘制的

**Comment by tyzlmjj** [comment]
背景的波纹切换是我自己写的，4.0以上效果都一样，但是没有官方的波纹效果那么细致

**Comment by mattxzhang** [comment]
哪段代码是绘制波纹的?找了半天没找到。。。

**Comment by tyzlmjj** [comment]
https://github.com/tyzlmjj/PagerBottomTabStrip/blob/master/pager-bottom-tab-strip/src/main/java/me/majiajie/pagerbottomtabstrip/ChangeColorsView.java
