### ISSUE TITLE
不使用ViewPager,设置选中下标的tab，首次加载不执行回调

### ISSUE THREAD

**Issue by weiweipang** [tyzlmjj/PagerBottomTabStrip#63]
不想使用项目中的viewPager，只是想根据选中的tab更换fragment，设置setSelect()后首次加载，tab回选中，但onSelected(int index,int old)方法不会调用,手动切换才会执行

**Comment by tyzlmjj** [comment]
是的，初次加载默认选中第一个，是不会产生回调的
