### ISSUE TITLE
Ripple effect on tab clicked is overlapping the tabview

### ISSUE THREAD

**Issue by muhrifqii** [tyzlmjj/PagerBottomTabStrip#68]
I set the height of tabview to `56dp` but the circular ripple effect onTabClicked is much larger than the height (out of view bounds). I am using 2 tab item with default mode but with tint enabled. I am using the androidx lib

**Comment by tyzlmjj** [comment]
My English is bad. So I don't quite understand what you mean. Do you want the ripple effect to not exceed the view range? (From Google Translator)

**Comment by muhrifqii** [comment]
Yes, the ripple effect should not exceeded the view range of TabView item. I am using the androidx dependencies.

**Comment by tyzlmjj** [comment]
If you build with material (), you can set elevation properties in XML

**Comment by muhrifqii** [comment]
It;s still overlapping the tabview

![Screenshot_1564014763fa](https://user-images.githubusercontent.com/6963502/61837454-110bb300-aeaf-11e9-8726-a1bd5a5e9872.png)

**Comment by tyzlmjj** [comment]
like this
```xml
<me.majiajie.pagerbottomtabstrip.PageNavigationView
        ...
        android:elevation="8dp" />
```

**Comment by muhrifqii** [comment]
I already did that @tyzlmjj , and had no effect

**Comment by tyzlmjj** [comment]
you can see my [DEMO](https://github.com/tyzlmjj/PagerBottomTabStrip/releases/download/2.3.0X/Demo.apk)

use ADB install
```
adb install -t [apk]
```
