### ISSUE TITLE
一个不成熟的小建议

### ISSUE THREAD

**Issue by maoai-xianyu** [tyzlmjj/PagerBottomTabStrip#69]
可以在library 种添加一下尺寸的适配，建议建议

**Comment by tyzlmjj** [comment]
怎样的适配？你可以具体描述下

**Comment by maoai-xianyu** [comment]
https://github.com/ladingwu/dimens_sw   这个不错。因为我一直在用你的，你的这个开源的是面向手机的，所以底部的icon的大小写死为 24dp, 字的大小写死为 12sp。 我们最近有个机构用我们的app,机构用了大量的安卓pad, 所以适配起来，确实有点丑。

**Comment by tyzlmjj** [comment]
pad的应用确实重来没有开发过，这个大小适配的话我会再看看

**Comment by maoai-xianyu** [comment]
![image](https://user-images.githubusercontent.com/17868022/64005049-1f9a5980-cb42-11e9-8fbf-0a4659e38aaa.png)
上面的图，是在你的源码上改的。下面的这个图是直接用你的库的显示，小米的pad
适配后![image](https://user-images.githubusercontent.com/17868022/64005610-558c0d80-cb43-11e9-94be-dc4602e57536.png)

**Comment by maoai-xianyu** [comment]
小米的pad 适配后
![image](https://user-images.githubusercontent.com/17868022/64005706-79e7ea00-cb43-11e9-88ab-e45e674815a9.png)
小米的pad 适配前
![image](https://user-images.githubusercontent.com/17868022/64006141-4e193400-cb44-11e9-9ee3-6f677eecca81.png)

**Comment by tyzlmjj** [comment]
了解了！主要身边没有平板，从来没测过。过段时间我去买个平板回来测试下兼容性！

**Comment by maoai-xianyu** [comment]
ok

**Comment by tyzlmjj** [comment]
@maoai-xianyu 我昨天在平板上运行了Demo 并没有出现你图中的问题！你能在你的平板上运行一下我的[DEMO.apk](https://github.com/tyzlmjj/PagerBottomTabStrip/releases/download/2.3.0X/Demo.apk)看看吗？

**Comment by maoai-xianyu** [comment]
号线你的demo.apk 是不是有问题呀？我手机上和平板上都安装不了

**Comment by tyzlmjj** [comment]
那是Debug版本的apk

你可以这样安装
```
adb install -t [apk]
```

**Comment by maoai-xianyu** [comment]
是真的很奇怪呀。

**Comment by maoai-xianyu** [comment]
真尴尬，我的显示就是之前的截图。我在代码里面用的是的 CustomActivity
```
 NavigationController navigationController = tab.custom()
                .addItem(newItem(R.drawable.ic_restore_gray_24dp, R.drawable.ic_restore_teal_24dp, "Recents"))
                .addItem(newItem(R.drawable.ic_favorite_gray_24dp, R.drawable.ic_favorite_teal_24dp, "Favorites"))
                .addItem(newItem(R.drawable.ic_nearby_gray_24dp, R.drawable.ic_nearby_teal_24dp, "Nearby"))
                .build();
```   我的显示有问题，但是你的demo没有问题。真的纠结了。你可以下载下我们的app   盒子鱼学生版，可以看下。

**Comment by maoai-xianyu** [comment]
很感谢你一直在回复我的问题，我也不知道哪里有问题了。不会是我app适配的问题吧？很困惑呀

**Comment by tyzlmjj** [comment]
现在平板不在身边测不了。
假如我的Demo没有问题的话，那很大可能是你app处理问题了。你可以检查下是否使用了第三方的屏幕适配的类库，或者可以把你构建导航栏的方法单独复制出来新建个APP看看有没问题。

**Comment by maoai-xianyu** [comment]
好的，感谢指导。你很不错的，谢谢哦
