### ISSUE TITLE
图片有阴影

### ISSUE THREAD

**Issue by zpfang9008** [tyzlmjj/PagerBottomTabStrip#7]
![image](https://cloud.githubusercontent.com/assets/7222185/16145030/5f6a0322-34a9-11e6-91e0-8305ab4d04f5.png)
有阴影。
.setDefaultIcon(R.drawable.ic_home_normal)
                .setSelectedIcon(R.drawable.ic_home_chosen)
                .setText("首页")
                .setTag("A")
                .build(); ，
没有setcolor

**Comment by tyzlmjj** [comment]
应该是你的图片问题，把空白都裁剪完

**Comment by zpfang9008** [comment]
是图片的问题，没发现。
