### ISSUE TITLE
禁止加载

### ISSUE THREAD

**Issue by 979881765** [tyzlmjj/PagerBottomTabStrip#70]
因为可能有特殊逻辑，怎么样让点击 item 不让跳转页面

**Comment by tyzlmjj** [comment]
你是用了`setupWithViewPager`方法配合`ViewPager`使用对吧，你可以不用这个自动适配的方法，用`addSimpleTabItemSelectedListener`这个方法

**Comment by 979881765** [comment]
好的，我试试

**Comment by kingslou** [comment]
赞一个
