### ISSUE TITLE
请问下不能单独只设置文字吗，设置图片null 就空指针啦

### ISSUE THREAD

**Issue by sunnnydaydev** [tyzlmjj/PagerBottomTabStrip#73]

**Comment by tyzlmjj** [comment]
`material`构建的话需要规范一点，你只设置文字的话可以看我的Demo，用自定义构建就可以了

**Comment by sunnnydaydev** [comment]
ok 谢谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"家杰"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 晚上7:06
收件人:&nbsp;"tyzlmjj/PagerBottomTabStrip"<PagerBottomTabStrip@noreply.github.com&gt;;
抄送:&nbsp;"晴天"<1246771571@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tyzlmjj/PagerBottomTabStrip] 请问下不能单独只设置文字吗，设置图片null 就空指针啦 (#73)




material构建的话需要规范一点，你只设置文字的话可以看我的Demo，用自定义构建就可以了
