### ISSUE TITLE
Android 11可能的问题

### ISSUE THREAD

**Issue by reneargento** [tyzlmjj/PagerBottomTabStrip#75]
我正在使用Android 11开发人员预览版2进行测试。
似乎未显示该选项卡。
是否已通过Android 11验证？

**Comment by tyzlmjj** [comment]
还没在11上测试过。你是安装的我的demo测试的吗？

**Comment by reneargento** [comment]
您的demo工作好。问题出在我的应用的bottom inset 在Android 11中。谢谢！
