### ISSUE TITLE
可以和viewpager2配合使用吗

### ISSUE THREAD

**Issue by yxmFromTheMoon** [tyzlmjj/PagerBottomTabStrip#76]

**Comment by tyzlmjj** [comment]
当然可以的，监听事件就可以了。

**Comment by yxmFromTheMoon** [comment]
不行啊，我依赖的androidx怎么没看到支持viewpager2,
  ViewPager2 mViewPager;
 mController.setupWithViewPager(mViewPager);//报错

**Comment by tyzlmjj** [comment]
不需要使用这个方法，用添加监听的方法，自己去控制viewpager2

**Comment by yxmFromTheMoon** [comment]
可以添加点击动画效果吗，用帧动画实现的那种

**Comment by tyzlmjj** [comment]
@yxmFromTheMoon 用自定义构建可以实现`.custom()`
不同的问题可以新开Issue的！
