### ISSUE TITLE
2.2.5版本 xml的background属性不生效

### ISSUE THREAD

**Issue by 15766736837** [tyzlmjj/PagerBottomTabStrip#78]
2.2.5版本 xml的background属性不生效

**Comment by tyzlmjj** [comment]
什么意思？

**Comment by 15766736837** [comment]
![1589512216(1)](https://user-images.githubusercontent.com/23132489/82007452-d9b7fe00-969c-11ea-83e9-4d2a941eb3df.jpg)
![微信图片_20200515111112](https://user-images.githubusercontent.com/23132489/82007458-dcb2ee80-969c-11ea-835b-a73d64b8bafe.jpg)

**Comment by 15766736837** [comment]
background想设置一个shape的但是没有效果 试了下改颜色也是没有效果

**Comment by tyzlmjj** [comment]
是不是每个tab上有背景覆盖了

**Comment by 15766736837** [comment]
emmm 真的是给tab的背景覆盖了 已经解决啦 谢谢
