### ISSUE TITLE
阴影不能取消

### ISSUE THREAD

**Issue by hongqinghe** [tyzlmjj/PagerBottomTabStrip#80]
![Xnip2020-11-06_15-16-29](https://user-images.githubusercontent.com/25189458/98337390-83bc8580-2043-11eb-91a5-de85d4969ae9.jpg)

**Comment by tyzlmjj** [comment]
这是底下布局的背景颜色，没有阴影的

**Comment by hongqinghe** [comment]
OK，已解决
