### ISSUE TITLE
why no support viewPager2？

### ISSUE THREAD

**Issue by chenyusheng** [tyzlmjj/PagerBottomTabStrip#84]
why no support viewPager2？

**Comment by tyzlmjj** [comment]
这个库是底部导航，点击事件都是有回调的，没有不支持ViewPager2的说法。你可能是想要一个简便的方法直接绑定到ViewPager2，但是如果我写在类库里面会造成不必要的依赖项，不使用ViewPager2的用户会产生无用的依赖项

**Comment by chenyusheng** [comment]
是的，就是setupWithViewPager（）可以直接绑定 viewpager2。
那现在看样子是只能自己直接通过回调和 viewpager2交互了
